//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadRelacionada
    {
        public int idActividadRelacionada { get; set; }
        public int idActividadPadre { get; set; }
        public int idActividadHijo { get; set; }
        public string comentario { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Actividad Actividad1 { get; set; }
    }
}
