//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjuntoProyecto
    {
        public int idAdjuntoProyecto { get; set; }
        public int idProyecto { get; set; }
        public int idAdjunto { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Adjuntos Adjuntos { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
