//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjuntoActividad
    {
        public int idAdjuntoActividad { get; set; }
        public int idAdjunto { get; set; }
        public int idActividad { get; set; }
        public int idUsuario { get; set; }
        public int fechaCreacion { get; set; }
    
        public virtual Adjuntos Adjuntos { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Actividad Actividad { get; set; }
    }
}
