//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoCambiosDeEstado
    {
        public int idHistorico { get; set; }
        public int idUsuraio { get; set; }
        public int idEstadoActividad { get; set; }
        public string observacion { get; set; }
    
        public virtual EstadoActividad EstadoActividad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
